### ISSUE TITLE
[feature request]  merge dev-bypass-logs and obfuscation branches 

### ISSUE THREAD

**Issue by thesle3p** [cobbr/ObfuscatedEmpire#10]
Any chance you can add the dev-bypass-logs features to the obfuscated empire branch? Would be great to use both feature sets in tandem.

**Comment by cobbr** [comment]
Great idea! The 2.0_beta and dev-bypass-logs branches both exist as PRs w/ Empire right now, so can't make commits to those. I'll merge them and put that as the master branch, since the master branch is super outdated at this point anyway. Thanks for the idea.

**Comment by cobbr** [comment]
Merged them into master :) b6517ca
