### ISSUE TITLE
Error server

### ISSUE THREAD

**Issue by LIZySARA** [cobbr/ObfuscatedEmpire#12]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)
Kali linux 2017.1

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Error when launching the vbs server

## Screenshot of error, embedded text output, or Pastebin link to the error

![screenshot_1](https://user-images.githubusercontent.com/22563762/28627614-36e2ee78-721a-11e7-8294-d0ef66fbd8ac.png)

**Comment by cobbr** [comment]
Thanks! I'll look into this soon.

**Comment by cobbr** [comment]
Hey @LIZySARA, sorry this took a while. I believe I've fixed this in ef1478de77990ef9a22b8ee52780ff7511a3c621

Could you give it a test to be sure it's fixed?

**Comment by LIZySARA** [comment]
Give error when Obfuscate is True

![error otrue](https://user-images.githubusercontent.com/22563762/29952134-645efea2-8ebf-11e7-8dd1-342bde802e99.png)



it's fixed when Obfuscate value is False 

![t](https://user-images.githubusercontent.com/22563762/29952304-71f1951a-8ec0-11e7-8f02-4a82cbcfc427.png)

**Comment by cobbr** [comment]
Thanks @LIZySARA, I'll give this another look. vbscript will be the death of me.

**Comment by cobbr** [comment]
I think this is finally fixed :) as of: 89d0deb63a6fa2a10a48dea0bb1d3c69fe52672a (empire-dev branch)

Hopefully will be merged to Empire soon, PR is in.

Feel free to test and let me know if it works at @LIZySARA, will close if so.
