### ISSUE TITLE
The term 'Invoke-Obfuscation' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by okiwoki** [cobbr/ObfuscatedEmpire#2]
## Empire Version
1.6.0

## OS Information (Linux flavor, Python version)
Kali Rolling 2016.2

## Any additional information

This looks like a two-part error.

After setting up a listener and setting "Obfuscated" to true in the "launcher" stager options. The following error is outputted before returning to the main menu:

Invoke-Obfuscation : The term 'Invoke-Obfuscation' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Invoke-Obfuscation -ScriptPath /opt/ObfuscatedEmpire/data/misc/ToObfu ...
+
    + CategoryInfo          : ObjectNotFound: (Invoke-Obfuscation:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
[!] Exception: [Errno 2] No such file or directory: '/opt/ObfuscatedEmpire/data/misc/ObfuscatedEmpire/data/misc/Obfuscated.ps1'

**Comment by cobbr** [comment]
Looks like the `Invoke-Obfuscation` files aren't getting copied to a folder in the `PSModulePath`. The setup script attempts to copy them to the `/usr/local/share/powershell/Modules` directory. A few ideas:

* Check to see if powershell installed correctly. Just run `powershell` from a terminal and see if you get a powershell console.
* Check if the `Invoke-Obfuscation` folder exists in `/usr/local/share/powershell/Modules`.
* If either of those fail, run `setup/install.sh` again and provide the output so we can figure out what's going wrong.

**Comment by okiwoki** [comment]
Looks like the install didn't copy over the powershell module and didn't create the directory.

>cp: cannot create directory '/usr/local/share/powershell/Modules': No such file or directory

After I created the directory and ran the install.sh again, everything is working.

**Comment by cobbr** [comment]
Glad you got it working! Looks like this was a bug where the install.sh script assumed the `/usr/local/share/powershell/Modules` folder already existed. I thought the powershell installation created that directory, looks like it doesn't. Thanks a bunch for reporting the bug, it should be fixed in the latest commit.

**Comment by cobbr** [comment]
Commit 6ea1f18c34f61f75c3055cd002cf654aa9c3cd4e closes #2
